IF object_id('P_ADD_STOCK_PRODUCT') is not null
	DROP PROC P_ADD_STOCK_PRODUCT;
GO	

CREATE PROC P_ADD_STOCK_PRODUCT
@ID INT,
@STOCK INT
AS 
BEGIN
	UPDATE PRODUCTS
	SET STOCK = STOCK + @STOCK
	WHERE ID = @ID
END
GO	