IF object_id('DELETE_DB') is not null
  DROP PROC DELETE_DB; 
GO

CREATE PROC DELETE_DB 
AS
BEGIN
	DELETE FROM BILL_DETAILS
	DBCC CHECKIDENT(BILL_DETAILS, RESEED,0)
	DELETE FROM BILLS
	DBCC CHECKIDENT (BILLS, RESEED,0)
	DELETE FROM CUSTOMERS
	DBCC CHECKIDENT (CUSTOMERS, RESEED,0)
	DELETE FROM TYPES_CLIENT
	DBCC CHECKIDENT (TYPES_CLIENT, RESEED,0)
	DELETE FROM PRODUCTS
	DBCC CHECKIDENT (PRODUCTS, RESEED,0)
END
GO

IF object_id('DB_POPULATE') is not null
  DROP PROC DB_POPULATE; 
GO

CREATE PROC DB_POPULATE AS
BEGIN    
	INSERT INTO TYPES_CLIENT (DESCRIPTION, IVA) VALUES ('MONOTRIBUTISTA', 1.105);
	INSERT INTO TYPES_CLIENT (DESCRIPTION, IVA) VALUES ('RESPONSABLE INSCRIPTO', 1.21);
	
	INSERT INTO CUSTOMERS (NAME, SURNAME, ID_TYPE_CLIENT) VALUES ('DANI', 'SANZ', 1);
	INSERT INTO CUSTOMERS (NAME, SURNAME, ID_TYPE_CLIENT) VALUES ('JULIAN', 'MARK', 2);
	
	INSERT INTO PRODUCTS (DESCRIPTION, PRICE, STOCK) VALUES ('MOUSE', 500.0, 4);
	INSERT INTO PRODUCTS (DESCRIPTION, PRICE, STOCK) VALUES ('HEADS PHONE', 1000.0, 5);
	
	INSERT INTO BILLS (ID_CUSTOMER) VALUES (1);
	INSERT INTO BILLS (ID_CUSTOMER) VALUES(2);
	
	INSERT INTO BILL_DETAILS (ID_BILL, ID_PRODUCT, AMOUNT, PRICE) VALUES (1, 1, 2, 500.00);
	INSERT INTO BILL_DETAILS (ID_BILL, ID_PRODUCT, AMOUNT, PRICE) VALUES (1, 2, 1, 1000.00);
	
	INSERT INTO BILL_DETAILS (ID_BILL, ID_PRODUCT, AMOUNT, PRICE) VALUES (2, 2, 2, 1000.00);
	INSERT INTO BILL_DETAILS (ID_BILL, ID_PRODUCT, AMOUNT, PRICE) VALUES (2, 1, 1, 500.00);

END
GO

IF object_id('DB_REBOOT') is not null
  DROP PROC DB_REBOOT; 
GO

CREATE PROC DB_REBOOT AS 
BEGIN	
	EXEC DELETE_DB
	EXEC DB_POPULATE	
END
GO