IF object_id('P_INSERT_BILL_DETAIL') is not null
	DROP PROC P_INSERT_BILL_DETAIL;
GO	

CREATE PROC P_INSERT_BILL_DETAIL
@ID_BILL INT,
@ID_PRODUCT INT,
@AMOUNT INT
AS 
BEGIN
	INSERT INTO BILL_DETAILS (ID_BILL, ID_PRODUCT, AMOUNT, PRICE) 
	VALUES (@ID_BILL, @ID_PRODUCT, @AMOUNT, (SELECT P.PRICE FROM PRODUCTS P WHERE P.ID = @ID_PRODUCT));
END
GO	
